"""Build assets/data/resources.json for the hub website search index.

Entries are written compactly here as tuples and expanded to JSON objects, so
adding a resource is one line rather than six.

    (name, url, description, section, tags)
"""

import json
import pathlib

CE = "chemical-engineering"
CI = "chemoinformatics"
BE = "bioengineering"
ME = "medical-engineering"
GE = "general-engineering"
TP = "templates"
WF = "workflows"

DATA = {
    CE: [
        ("DWSIM", "https://dwsim.org",
         "CAPE-OPEN compliant steady-state and dynamic flowsheet simulator with a graphical editor and rigorous distillation.",
         "Process Simulation", ["c#", "gui", "cross-platform", "simulation"]),
        ("COCO Simulator", "https://www.cocosimulator.org",
         "Free CAPE-OPEN flowsheeting environment bundling the COFE editor, TEA thermodynamics server, and COUSCOUS unit operations.",
         "Process Simulation", ["windows", "gui", "cape-open"]),
        ("ChemSep", "https://www.chemsep.org",
         "Rigorous rate-based and equilibrium-stage column simulator; the LITE edition is free for up to 40 stages.",
         "Process Simulation", ["gui", "distillation", "commercial-free-tier"]),
        ("IDAES-PSE", "https://github.com/IDAES/idaes-pse",
         "Equation-oriented process systems engineering framework on Pyomo, with simultaneous design and control optimisation.",
         "Process Simulation", ["python", "equation-oriented", "optimisation"]),
        ("OpenModelica", "https://openmodelica.org",
         "Equation-based modelling environment for the Modelica language, strong for dynamic process models.",
         "Process Simulation", ["modelica", "gui", "dynamic"]),
        ("WaterTAP", "https://github.com/watertap-org/watertap",
         "IDAES-based library for water treatment flowsheets including RO, ion exchange, and crystallisation, with costing.",
         "Process Simulation", ["python", "water-treatment"]),
        ("Cantera", "https://cantera.org",
         "Object-oriented toolkit for chemical kinetics, thermodynamics, and transport, with reactor networks and flame solvers.",
         "Thermodynamics & Properties", ["python", "c++", "matlab", "kinetics"]),
        ("CoolProp", "http://www.coolprop.org",
         "Thermophysical properties for ~122 fluids and humid air using Helmholtz-energy equations of state.",
         "Thermodynamics & Properties", ["c++", "python", "excel", "matlab"]),
        ("thermo", "https://github.com/CalebBell/thermo",
         "Pure-Python chemical engineering thermodynamics: VLE/LLE flashes, cubic and SAFT EOS, activity coefficient models.",
         "Thermodynamics & Properties", ["python", "thermodynamics"]),
        ("chemicals", "https://github.com/CalebBell/chemicals",
         "Database of pure-component constants, correlations, and critical properties with careful literature sourcing.",
         "Thermodynamics & Properties", ["python", "dataset"]),
        ("fluids", "https://github.com/CalebBell/fluids",
         "Fluid dynamics correlations for pressure drop, friction factors, control valve sizing, and two-phase flow.",
         "Thermodynamics & Properties", ["python", "hydraulics"]),
        ("ht", "https://github.com/CalebBell/ht",
         "Heat transfer correlations: conduction, convection, boiling, condensation, radiation, and exchanger effectiveness-NTU.",
         "Unit Operations", ["python", "heat-transfer"]),
        ("Clapeyron.jl", "https://github.com/ClapeyronThermo/Clapeyron.jl",
         "Julia framework for equations of state covering cubics, SAFT variants, activity models, and electrolytes.",
         "Thermodynamics & Properties", ["julia", "thermodynamics"]),
        ("teqp", "https://github.com/usnistgov/teqp",
         "NIST templated equation-of-state library giving exact derivatives via automatic differentiation.",
         "Thermodynamics & Properties", ["c++", "python", "nist"]),
        ("PHREEQC", "https://www.usgs.gov/software/phreeqc-version-3",
         "USGS geochemical speciation and reaction-path modelling, the standard for aqueous equilibria and scaling.",
         "Thermodynamics & Properties", ["c++", "gui", "geochemistry"]),
        ("ASALI", "https://github.com/srebughini/ASALI",
         "GUI and library for catalytic reactor modelling (batch, CSTR, 1D heterogeneous PFR) built on Cantera.",
         "Reaction Engineering", ["c++", "python", "gui", "catalysis"]),
        ("Reaction Mechanism Generator", "https://rmg.mit.edu",
         "Automatically constructs detailed kinetic mechanisms from thermochemistry and rate rules.",
         "Reaction Engineering", ["python", "kinetics", "mechanism"]),
        ("Pyomo", "https://www.pyomo.org",
         "Algebraic modelling language in Python for LP, MILP, NLP, MINLP, and DAE-constrained problems.",
         "Optimisation", ["python", "optimisation"]),
        ("CasADi", "https://web.casadi.org",
         "Symbolic framework for nonlinear optimisation and algorithmic differentiation, strong for optimal control.",
         "Optimisation", ["python", "matlab", "c++", "optimisation"]),
        ("Ipopt", "https://github.com/coin-or/Ipopt",
         "Interior-point solver for large-scale nonlinear programs, the default NLP backend for open process optimisation.",
         "Optimisation", ["c++", "solver"]),
        ("GEKKO", "https://gekko.readthedocs.io",
         "Python package for dynamic optimisation, parameter estimation, and nonlinear MPC with a gentle on-ramp.",
         "Optimisation", ["python", "mpc", "optimisation"]),
        ("HiGHS", "https://highs.dev",
         "High-performance open LP and MIP solver, now the default in SciPy and fast enough for real scheduling problems.",
         "Optimisation", ["c++", "solver"]),
        ("python-control", "https://python-control.readthedocs.io",
         "Classical and state-space control: transfer functions, root locus, Bode, LQR, and system identification helpers.",
         "Process Control", ["python", "control"]),
        ("do-mpc", "https://www.do-mpc.com",
         "Model predictive control and moving-horizon estimation on CasADi, with robust multi-stage MPC.",
         "Process Control", ["python", "mpc", "control"]),
        ("SIPPY", "https://github.com/CPCLAB-UNIPI/SIPPY",
         "System identification for process models: ARX, ARMAX, subspace, and output-error methods from step or PRBS data.",
         "Process Control", ["python", "system-id"]),
        ("TCLab", "https://apmonitor.com/heat.htm",
         "Low-cost Arduino temperature control kit with an open Python API, the standard hardware platform for teaching PID and MPC.",
         "Process Control", ["hardware", "python", "course"]),
        ("ALOHA", "https://www.epa.gov/cameo/aloha-software",
         "EPA/NOAA atmospheric dispersion model for accidental chemical releases, with toxic and flammable footprints.",
         "Process Safety", ["gui", "safety", "dispersion"]),
        ("CAMEO Chemicals", "https://cameochemicals.noaa.gov",
         "Reactivity matrix and response information for ~6000 hazardous materials; check incompatibilities before mixing.",
         "Process Safety", ["database", "web", "safety"]),
        ("OSHA PSM standard", "https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.119",
         "The US process safety management rule, 29 CFR 1910.119, in full.",
         "Process Safety", ["standard", "regulatory", "safety"]),
        ("OpenFOAM", "https://www.openfoam.com",
         "General-purpose finite-volume CFD with solvers for multiphase, reacting, and turbulent flow.",
         "Computational Fluid Dynamics", ["c++", "linux", "cfd"]),
        ("NIST Chemistry WebBook", "https://webbook.nist.gov/chemistry",
         "Thermochemical, thermophysical, and spectral data for tens of thousands of compounds, free for interactive use.",
         "Data & Benchmarks", ["database", "reference", "nist"]),
        ("Tennessee Eastman process", "https://github.com/camaramm/tennessee-eastman-profBraatz",
         "The canonical plant-wide control and fault-detection benchmark, with 21 fault scenarios.",
         "Data & Benchmarks", ["matlab", "benchmark", "control"]),
        ("LearnChemE", "https://learncheme.com",
         "Hundreds of short screencasts, interactive simulations, and ConcepTests across the undergraduate curriculum.",
         "Learning Resources", ["course", "interactive", "free"]),
        ("APMonitor Process Dynamics and Control", "https://apmonitor.com/pdc",
         "Free 12-week course on process control with Python exercises and TCLab hardware.",
         "Learning Resources", ["course", "python", "control", "free"]),
        ("Chemical Process Dynamics and Controls (LibreTexts)", "https://eng.libretexts.org/Bookshelves/Industrial_and_Systems_Engineering/Chemical_Process_Dynamics_and_Controls_(Woolf)",
         "Complete open textbook on process dynamics and control with worked examples.",
         "Learning Resources", ["book", "free", "control"]),
        ("MIT OCW 10.10 Chemical Engineering Analysis", "https://ocw.mit.edu/courses/10-10-introduction-to-chemical-engineering-analysis-fall-2005/",
         "Full lecture notes and problem sets on material balances and process analysis.",
         "Learning Resources", ["course", "free", "balances"]),
    ],
    CI: [
        ("RDKit", "https://www.rdkit.org",
         "The foundational open cheminformatics toolkit: substructure search, conformers, descriptors, fingerprints, drawing.",
         "Molecular Representations", ["python", "c++", "java", "cheminformatics"]),
        ("Open Babel", "https://openbabel.org",
         "Format conversion across 110+ chemical file formats, plus force-field optimisation and conformer search.",
         "Molecular Representations", ["c++", "python", "cli"]),
        ("datamol", "https://docs.datamol.io",
         "Ergonomic wrapper over RDKit that makes common molecule handling a one-liner with sane sanitisation defaults.",
         "Molecular Representations", ["python"]),
        ("SELFIES", "https://github.com/aspuru-guzik-group/selfies",
         "String representation where every string is a valid molecule, removing a class of failure from generative models.",
         "Molecular Representations", ["python", "generative"]),
        ("ChEMBL Structure Pipeline", "https://github.com/chembl/ChEMBL_Structure_Pipeline",
         "Standardisation, salt stripping, charge normalisation, and tautomer canonicalisation as ChEMBL applies them.",
         "Molecular Representations", ["python", "standardisation"]),
        ("InChI", "https://www.inchi-trust.org",
         "IUPAC's canonical structure identifier and its InChIKey hash, the closest thing chemistry has to a primary key.",
         "File Formats", ["standard", "c", "identifier"]),
        ("KNIME Analytics Platform", "https://www.knime.com",
         "Visual workflow environment; community and RDKit extensions make it a full cheminformatics stack without code.",
         "Pipelines", ["gui", "java", "commercial-free-tier", "workflow"]),
        ("Mordred", "https://github.com/mordred-descriptor/mordred",
         "Calculates ~1800 2D and 3D molecular descriptors with clear provenance for each definition.",
         "Descriptors & Fingerprints", ["python", "descriptors"]),
        ("scikit-mol", "https://github.com/EBjerrum/scikit-mol",
         "RDKit featurisers as scikit-learn transformers, so molecules drop into a Pipeline with proper cross-validation.",
         "Descriptors & Fingerprints", ["python", "machine-learning"]),
        ("DeepChem", "https://deepchem.io",
         "Batteries-included library for molecular machine learning: featurisers, splitters, model zoo, MoleculeNet loaders.",
         "QSAR / Machine Learning", ["python", "tensorflow", "pytorch", "machine-learning"]),
        ("Chemprop", "https://chemprop.readthedocs.io",
         "Directed message-passing neural networks for property prediction; a strong baseline that is hard to beat on small data.",
         "QSAR / Machine Learning", ["python", "pytorch", "gnn"]),
        ("QSARtuna", "https://github.com/MolecularAI/QSARtuna",
         "Automated QSAR model building with hyperparameter search, uncertainty estimation, and reproducible model cards.",
         "QSAR / Machine Learning", ["python", "qsar"]),
        ("MACE", "https://github.com/ACEsuit/mace",
         "Equivariant machine-learning interatomic potentials with near-DFT accuracy for energies and forces at MD cost.",
         "QSAR / Machine Learning", ["python", "pytorch", "potentials"]),
        ("REINVENT", "https://github.com/MolecularAI/REINVENT4",
         "Generative molecular design with reinforcement learning and scoring components for multi-parameter optimisation.",
         "QSAR / Machine Learning", ["python", "generative"]),
        ("AiZynthFinder", "https://github.com/MolecularAI/aizynthfinder",
         "Monte-Carlo tree search retrosynthesis with template extraction and stock-compound termination; runs on a laptop.",
         "Reaction Prediction", ["python", "retrosynthesis"]),
        ("rxnmapper", "https://github.com/rxn4chemistry/rxnmapper",
         "Atom-mapping from transformer attention weights, fast and accurate without reaction templates.",
         "Reaction Prediction", ["python", "reactions"]),
        ("RDChiral", "https://github.com/connorcoley/rdchiral",
         "Correct application of retrosynthetic templates with chirality preserved, the piece naive template code gets wrong.",
         "Reaction Prediction", ["python", "retrosynthesis"]),
        ("Psi4", "https://psicode.org",
         "Modern open quantum chemistry package (DFT, MP2, coupled cluster) with a clean Python API for scripted workflows.",
         "Quantum Chemistry", ["c++", "python", "dft"]),
        ("PySCF", "https://pyscf.org",
         "Quantum chemistry as a Python library rather than an input-file program, ideal for method development.",
         "Quantum Chemistry", ["python", "dft"]),
        ("xtb", "https://github.com/grimme-lab/xtb",
         "Semi-empirical tight-binding methods (GFN1/GFN2) giving usable geometries orders of magnitude faster than DFT.",
         "Quantum Chemistry", ["fortran", "cli", "semi-empirical"]),
        ("CREST", "https://github.com/crest-lab/crest",
         "Conformer and rotamer ensemble sampling driven by xtb, the standard step before any DFT refinement.",
         "Quantum Chemistry", ["fortran", "cli", "conformers"]),
        ("OpenMM", "https://openmm.org",
         "GPU-accelerated molecular dynamics with a Python API and custom force expressions, usable as a library.",
         "Quantum Chemistry", ["python", "c++", "gpu", "md"]),
        ("ASE", "https://wiki.fysik.dtu.dk/ase/",
         "Python interface driving dozens of calculators with one API, so you can swap xtb for DFT without rewriting.",
         "Quantum Chemistry", ["python", "atomistic"]),
        ("PubChem", "https://pubchem.ncbi.nlm.nih.gov",
         "~120 million compounds with bioassay data, safety information, and a well-documented REST API. Public domain.",
         "Chemical Databases", ["database", "api", "public-domain"]),
        ("ChEMBL", "https://www.ebi.ac.uk/chembl/",
         "Manually curated bioactivity data from the medicinal chemistry literature, with measured activities against targets.",
         "Chemical Databases", ["database", "api", "bioactivity"]),
        ("ZINC22", "https://cartblanche22.docking.org",
         "Billions of purchasable compounds in 3D ready for docking, filterable by vendor and lead-likeness.",
         "Chemical Databases", ["database", "docking"]),
        ("Crystallography Open Database", "https://www.crystallography.net/cod/",
         "Open collection of ~500 000 experimental crystal structures of small molecules and minerals.",
         "Chemical Databases", ["database", "public-domain", "crystallography"]),
        ("Open Reaction Database", "https://open-reaction-database.org",
         "Community reaction dataset with structured conditions and yields, machine-readable by design.",
         "Chemical Databases", ["database", "api", "reactions"]),
        ("3Dmol.js", "https://3dmol.csb.pitt.edu",
         "WebGL molecular viewer that embeds in any page with a few lines of JavaScript.",
         "Visualisation", ["javascript", "web", "viewer"]),
        ("NGL Viewer / nglview", "https://github.com/nglviewer/nglview",
         "High-performance structure viewer with a Jupyter widget, good for large biomolecular assemblies.",
         "Visualisation", ["javascript", "python", "jupyter", "viewer"]),
        ("Mol*", "https://molstar.org",
         "The viewer behind RCSB PDB and PDBe, handling very large structures and volumetric data in the browser.",
         "Visualisation", ["typescript", "web", "viewer"]),
        ("DataWarrior", "https://openmolecules.org/datawarrior/",
         "Free chemical data visualisation and analysis: scatter plots linked to structures, SAR tables, clustering.",
         "Visualisation", ["java", "gui", "analysis"]),
        ("MoleculeNet", "https://moleculenet.org",
         "The standard benchmark collection for molecular property prediction, with recommended splits.",
         "Benchmarks", ["benchmark", "dataset"]),
        ("Therapeutics Data Commons", "https://tdcommons.ai",
         "Curated machine learning tasks across ADMET, HTS, and synthesis with leaderboards and consistent splits.",
         "Benchmarks", ["benchmark", "python", "dataset"]),
        ("TeachOpenCADD", "https://projects.volkamerlab.org/teachopencadd/",
         "Structured talktorials covering compound data acquisition, filtering, docking, and machine learning.",
         "Learning Resources", ["notebooks", "course", "free"]),
        ("Practical Cheminformatics tutorials", "https://github.com/PatWalters/practical_cheminformatics_tutorials",
         "Notebook series on the tasks people actually do - clustering, SAR, model building - and their pitfalls.",
         "Learning Resources", ["notebooks", "free"]),
    ],
    BE: [
        ("COBRApy", "https://opencobra.github.io/cobrapy/",
         "Constraint-based reconstruction and analysis in Python: FBA, pFBA, FVA, gene deletions, model editing.",
         "Genome-Scale Models", ["python", "metabolic", "fba"]),
        ("COBRA Toolbox", "https://opencobra.github.io/cobratoolbox/",
         "The MATLAB counterpart to COBRApy, with a larger set of specialised thermodynamic and expression-integrated methods.",
         "Genome-Scale Models", ["matlab", "metabolic"]),
        ("Memote", "https://memote.readthedocs.io",
         "Standardised test suite scoring a metabolic model's quality - mass balance, annotation, consistency - as a report.",
         "Genome-Scale Models", ["python", "qa", "metabolic"]),
        ("CarveMe", "https://github.com/cdanielmachado/carveme",
         "Top-down metabolic reconstruction carving a species model out of a universal model in seconds.",
         "Genome-Scale Models", ["python", "metabolic"]),
        ("BiGG Models", "http://bigg.ucsd.edu",
         "Curated repository of high-quality genome-scale models with standardised identifiers and an API.",
         "Genome-Scale Models", ["database", "api", "metabolic"]),
        ("MICOM", "https://github.com/micom-dev/micom",
         "Community-level metabolic modelling for microbiomes, trading off community and individual growth.",
         "Genome-Scale Models", ["python", "microbiome"]),
        ("BioSTEAM", "https://biosteam.readthedocs.io",
         "Fast techno-economic analysis and process simulation for biorefineries, with costing and uncertainty propagation.",
         "Bioprocess Modelling", ["python", "tea", "biorefinery"]),
        ("PyFOOMB", "https://github.com/MicroPhen/pyFOOMB",
         "Object-oriented bioprocess modelling with parameter estimation and multi-experiment fitting.",
         "Bioprocess Modelling", ["python", "parameter-estimation"]),
        ("Tellurium", "http://tellurium.analogmachine.org",
         "Python environment for systems biology built on libRoadRunner and Antimony, with fast SBML simulation.",
         "Kinetic Modelling", ["python", "sbml", "systems-biology"]),
        ("COPASI", "https://copasi.org",
         "Biochemical network simulator with steady-state, time-course, stochastic, and parameter-estimation methods.",
         "Kinetic Modelling", ["c++", "gui", "systems-biology"]),
        ("BioNetGen", "https://bionetgen.org",
         "Rule-based modelling for systems with combinatorial complexity, where enumerating every species is hopeless.",
         "Kinetic Modelling", ["rule-based", "systems-biology"]),
        ("SBOL", "https://sbolstandard.org",
         "Synthetic Biology Open Language: the data standard for genetic designs, with Python and Java implementations.",
         "Synthetic Biology", ["standard", "python", "java"]),
        ("pydna", "https://github.com/BjornFJohansson/pydna",
         "Simulates cloning, Gibson assembly, and PCR in code so a construction plan is reproducible and diffable.",
         "Synthetic Biology", ["python", "cloning"]),
        ("DNA Chisel", "https://github.com/Edinburgh-Genome-Foundry/DnaChisel",
         "Sequence optimisation under constraints: codon usage, restriction sites, GC content, synthesis manufacturability.",
         "Synthetic Biology", ["python", "sequence-design"]),
        ("Cello", "https://github.com/CIDARLAB/cello",
         "Compiles Verilog descriptions of logic into genetic circuits with characterised gates.",
         "Synthetic Biology", ["java", "design-automation"]),
        ("SynBioHub", "https://synbiohub.org",
         "Repository for sharing genetic designs in SBOL with provenance and versioning.",
         "Synthetic Biology", ["web", "database"]),
        ("iGEM Registry of Standard Biological Parts", "http://parts.igem.org",
         "The community parts registry, with characterisation data of variable but often useful quality.",
         "Synthetic Biology", ["database", "community"]),
        ("ColabFold", "https://github.com/sokrypton/ColabFold",
         "AlphaFold2 and related models made runnable in a notebook in minutes rather than a cluster in days.",
         "Protein Engineering", ["python", "notebook", "structure-prediction"]),
        ("ESM / ESMFold", "https://github.com/facebookresearch/esm",
         "Protein language models for embeddings, variant effect prediction, and single-sequence structure prediction.",
         "Protein Engineering", ["python", "pytorch", "protein"]),
        ("ProteinMPNN", "https://github.com/dauparas/ProteinMPNN",
         "Inverse folding: given a backbone, propose sequences that fold to it, with high experimental success rates.",
         "Protein Engineering", ["python", "design"]),
        ("BRENDA", "https://www.brenda-enzymes.org",
         "The comprehensive enzyme kinetics database: kcat, Km, inhibitors, and conditions from the literature.",
         "Protein Engineering", ["database", "enzymes"]),
        ("FEBio", "https://febio.org",
         "Finite element solver purpose-built for biological materials: hyperelasticity, poroelasticity, growth and remodelling.",
         "Biomaterials", ["c++", "fea", "soft-tissue"]),
        ("PhysiCell", "http://physicell.org",
         "Agent-based simulator for multicellular systems with diffusive substrates, scaling to millions of cells.",
         "Tissue Engineering", ["c++", "agent-based"]),
        ("CompuCell3D", "https://compucell3d.org",
         "Multi-cell modelling environment using cellular Potts for morphogenesis, cell sorting, and tissue growth.",
         "Tissue Engineering", ["c++", "python", "gui"]),
        ("CellProfiler", "https://cellprofiler.org",
         "Pipeline-based quantitative image analysis for high-content screening, no coding required.",
         "Tissue Engineering", ["python", "gui", "imaging"]),
        ("Fiji / ImageJ", "https://fiji.sc",
         "Image analysis for histology, live-cell imaging, and scaffold characterisation, with a plugin for nearly everything.",
         "Tissue Engineering", ["java", "gui", "imaging"]),
        ("Biopython", "https://biopython.org",
         "Sequence handling, file parsing, and interfaces to the major biological databases.",
         "Bioinformatics", ["python", "sequences"]),
        ("nf-core", "https://nf-co.re",
         "Community-curated, peer-reviewed Nextflow pipelines with consistent structure and testing.",
         "Bioinformatics", ["nextflow", "workflow", "reproducibility"]),
        ("Bioconda", "https://bioconda.github.io",
         "Conda channel with 8000+ bioinformatics packages, making reproducible bio environments tractable.",
         "Bioinformatics", ["packaging", "conda"]),
        ("SBML", "https://sbml.org",
         "The systems biology markup language; a model that cannot export to SBML cannot easily be reused.",
         "Standards & Data", ["standard", "xml"]),
        ("BioModels", "https://www.ebi.ac.uk/biomodels/",
         "Repository of curated, annotated published models you can load and rerun.",
         "Standards & Data", ["database", "models"]),
        ("protocols.io", "https://www.protocols.io",
         "Versioned, citable experimental protocols - the fix for 'as previously described'.",
         "Standards & Data", ["platform", "protocols"]),
    ],
    ME: [
        ("3D Slicer", "https://www.slicer.org",
         "Comprehensive platform for medical image visualisation, segmentation, registration, and image-guided procedures.",
         "Medical Imaging", ["python", "c++", "gui", "imaging"]),
        ("ITK / SimpleITK", "https://itk.org",
         "The insight toolkit: registration and segmentation algorithms underpinning much of medical imaging.",
         "Medical Imaging", ["c++", "python", "imaging"]),
        ("pydicom", "https://pydicom.github.io",
         "Reading, modifying, and writing DICOM files in Python, the practical start for any imaging script.",
         "Medical Imaging", ["python", "dicom"]),
        ("Orthanc", "https://www.orthanc-server.com",
         "Lightweight standalone DICOM server with a REST API, ideal for research PACS and de-identification pipelines.",
         "Medical Imaging", ["c++", "dicom", "server"]),
        ("dcm4che", "https://www.dcm4che.org",
         "Full DICOM implementation: toolkit, PACS archive, and command-line utilities.",
         "Medical Imaging", ["java", "dicom"]),
        ("OHIF Viewer", "https://ohif.org",
         "Zero-footprint extensible web DICOM viewer, the basis for many research imaging platforms.",
         "Medical Imaging", ["javascript", "web", "dicom"]),
        ("MONAI", "https://monai.io",
         "PyTorch framework for medical imaging deep learning, with domain-specific transforms and networks.",
         "Medical Imaging", ["python", "pytorch", "deep-learning"]),
        ("nnU-Net", "https://github.com/MIC-DKFZ/nnUNet",
         "Self-configuring segmentation framework that remains a very strong baseline across modalities.",
         "Medical Imaging", ["python", "segmentation"]),
        ("TotalSegmentator", "https://github.com/wasserth/TotalSegmentator",
         "Segments 100+ anatomical structures in CT with one command, the fastest route from a scan to geometry.",
         "Medical Imaging", ["python", "segmentation"]),
        ("ITK-SNAP", "http://www.itksnap.org",
         "Focused, fast manual and semi-automatic segmentation tool, still what many use to produce ground truth.",
         "Medical Imaging", ["gui", "segmentation"]),
        ("deid", "https://github.com/pydicom/deid",
         "Rule-based removal of protected health information from DICOM headers and burned-in pixel text.",
         "Medical Imaging", ["python", "privacy", "dicom"]),
        ("OpenSim", "https://opensim.stanford.edu",
         "Musculoskeletal modelling and simulation: inverse kinematics and dynamics, static optimisation, forward simulation.",
         "Biomechanics", ["c++", "python", "matlab", "gui"]),
        ("Gibbon", "https://www.gibboncode.org",
         "MATLAB toolbox for computational biomechanics: meshing, FEBio interfacing, image-based model generation.",
         "Biomechanics", ["matlab", "fea"]),
        ("Pose2Sim", "https://github.com/perfanalytics/pose2sim",
         "Markerless motion capture from ordinary video into OpenSim-ready kinematics using multi-view pose estimation.",
         "Biomechanics", ["python", "motion-capture"]),
        ("PyDy", "https://www.pydy.org",
         "Multibody dynamics from symbolic equations of motion via SymPy, useful for prosthetics and exoskeleton studies.",
         "Biomechanics", ["python", "dynamics"]),
        ("NeuroKit2", "https://neuropsychology.github.io/NeuroKit/",
         "Processing and feature extraction for ECG, PPG, EDA, EMG, and respiration signals with sane defaults.",
         "Physiological Signals", ["python", "signals"]),
        ("MNE-Python", "https://mne.tools",
         "EEG and MEG analysis: preprocessing, source localisation, time-frequency, and statistics.",
         "Physiological Signals", ["python", "eeg"]),
        ("wfdb-python", "https://github.com/MIT-LCP/wfdb-python",
         "Reads PhysioNet waveform databases and implements the classic detection algorithms.",
         "Physiological Signals", ["python", "signals"]),
        ("OpenCOR", "https://opencor.ws",
         "Environment for editing and simulating CellML physiological models without writing solver code.",
         "Physiological Signals", ["gui", "c++", "cellml"]),
        ("FDA Guidance Documents", "https://www.fda.gov/regulatory-information/search-fda-guidance-documents",
         "Every current FDA guidance, free. Start with premarket submissions for device software functions.",
         "Regulatory & Standards", ["regulatory", "free", "fda"]),
        ("FDA 510(k) database", "https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpmn/pmn.cfm",
         "Searchable record of cleared devices and their summaries, the fastest way to find a predicate.",
         "Regulatory & Standards", ["database", "regulatory", "fda"]),
        ("EU MDR 2017/745", "https://eur-lex.europa.eu/eli/reg/2017/745/oj",
         "The EU Medical Device Regulation in full, in 24 languages, free.",
         "Regulatory & Standards", ["regulatory", "free", "eu"]),
        ("openregulatory guides", "https://openregulatory.com",
         "Free plain-language walkthroughs of MDR, IEC 62304, and ISO 14971 with downloadable templates.",
         "Regulatory & Standards", ["guide", "free", "regulatory"]),
        ("MAUDE adverse event database", "https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfmaude/search.cfm",
         "Reported device failures and adverse events; read your device category before designing, not after.",
         "Regulatory & Standards", ["database", "safety", "fda"]),
        ("Doorstop", "https://doorstop.readthedocs.io",
         "Requirements management in version-controlled text files with automated traceability matrices.",
         "Quality & Risk", ["python", "requirements", "traceability"]),
        ("Syft", "https://github.com/anchore/syft",
         "Generates software bills of materials, now expected in FDA premarket cybersecurity documentation.",
         "Quality & Risk", ["cli", "security", "sbom"]),
        ("HL7 FHIR", "https://www.hl7.org/fhir/",
         "The modern healthcare interoperability standard; the specification is free and the resource model is usable.",
         "Health Informatics", ["standard", "api", "free"]),
        ("HAPI FHIR", "https://hapifhir.io",
         "Complete Java FHIR implementation with a reference server, the default way to prototype against FHIR.",
         "Health Informatics", ["java", "fhir"]),
        ("OpenMRS", "https://openmrs.org",
         "Open electronic medical record platform deployed widely in low-resource settings.",
         "Health Informatics", ["java", "platform", "emr"]),
        ("OHDSI / OMOP CDM", "https://www.ohdsi.org",
         "Common data model and analytics stack for observational health research across institutions.",
         "Health Informatics", ["sql", "r", "standard"]),
        ("Synthea", "https://synthetichealth.github.io/synthea/",
         "Generates realistic synthetic patient records with full longitudinal histories, in FHIR and CSV. No privacy risk.",
         "Health Informatics", ["java", "dataset", "synthetic"]),
        ("PhysioNet", "https://physionet.org",
         "Waveform and clinical databases including MIMIC-IV, with credentialed access and clear data use agreements.",
         "Datasets", ["dataset", "clinical"]),
        ("The Cancer Imaging Archive", "https://www.cancerimagingarchive.net",
         "Large de-identified imaging collections with linked clinical data.",
         "Datasets", ["dataset", "imaging"]),
        ("Medical Segmentation Decathlon", "http://medicaldecathlon.com",
         "Ten segmentation tasks across organs and modalities, the standard cross-task benchmark.",
         "Datasets", ["dataset", "benchmark", "segmentation"]),
        ("MIT 2.75 Medical Device Design", "https://ocw.mit.edu/courses/2-75-medical-device-design-fall-2019/",
         "Full course on device design methodology with real project examples.",
         "Learning Resources", ["course", "free"]),
    ],
    GE: [
        ("FreeCAD", "https://www.freecad.org",
         "Parametric 3D CAD with a feature tree, assembly and FEM workbenches, and complete Python scripting.",
         "CAD & Geometry", ["python", "c++", "gui", "cad"]),
        ("OpenSCAD", "https://openscad.org",
         "Constructive solid geometry defined in code, so parts are diffable, reviewable, and parametric by construction.",
         "CAD & Geometry", ["cli", "gui", "cad"]),
        ("CadQuery", "https://cadquery.readthedocs.io",
         "Python API for building parametric solids on the OCCT kernel, fluent enough to be pleasant for real parts.",
         "CAD & Geometry", ["python", "cad"]),
        ("build123d", "https://build123d.readthedocs.io",
         "Modern successor to CadQuery's builder API with a cleaner selector model and good documentation.",
         "CAD & Geometry", ["python", "cad"]),
        ("KiCad", "https://www.kicad.org",
         "Schematic capture, PCB layout, and manufacturing outputs with a strong scripting API and no seat limits.",
         "CAD & Geometry", ["gui", "electronics", "pcb"]),
        ("LibreCAD", "https://librecad.org",
         "Focused 2D drafting for P&IDs, layouts, and shop drawings, reading and writing DXF.",
         "CAD & Geometry", ["c++", "gui", "drafting"]),
        ("trimesh", "https://trimsh.org",
         "Mesh loading, repair, boolean operations, and mass properties in Python, the glue for geometry pipelines.",
         "CAD & Geometry", ["python", "mesh"]),
        ("CalculiX", "http://www.calculix.de",
         "Nonlinear finite element solver with Abaqus-compatible input syntax: static, dynamic, thermal, and contact.",
         "CAE & FEA", ["fortran", "c", "fea"]),
        ("Code_Aster", "https://code-aster.org",
         "EDF's structural mechanics and thermomechanics solver, validated against a large public test suite.",
         "CAE & FEA", ["fortran", "python", "fea"]),
        ("Elmer FEM", "https://www.elmerfem.org",
         "Multiphysics FEM covering heat transfer, electromagnetics, acoustics, and fluid-structure interaction.",
         "CAE & FEA", ["fortran", "c++", "gui", "fea"]),
        ("Gmsh", "https://gmsh.info",
         "Mesh generator with a scripting language and CAD kernel integration, the default meshing step for open FEA.",
         "CAE & FEA", ["c++", "python", "meshing"]),
        ("PrePoMax", "https://prepomax.fs.um.si",
         "Friendly pre- and post-processor for CalculiX, making open FEA approachable for commercial-GUI users.",
         "CAE & FEA", ["gui", "fea", "windows"]),
        ("PyVista", "https://docs.pyvista.org",
         "Pythonic mesh and volume visualisation on VTK, ideal for notebooks and automated reporting.",
         "CAE & FEA", ["python", "visualisation"]),
        ("GNU Octave", "https://octave.org",
         "MATLAB-compatible environment; the fastest way to run existing coursework and toolboxes without a licence.",
         "Control Systems", ["octave", "matlab-compatible"]),
        ("ControlSystems.jl", "https://github.com/JuliaControl/ControlSystems.jl",
         "Julia control toolbox with robust control, model reduction, and automatic differentiation support.",
         "Control Systems", ["julia", "control"]),
        ("OpenPLC", "https://autonomylogic.com/openplc",
         "Open IEC 61131-3 PLC runtime and editor (ladder, structured text) that runs on a Raspberry Pi.",
         "Control Systems", ["plc", "iec-61131", "automation"]),
        ("GNU Radio", "https://www.gnuradio.org",
         "Software-defined radio and general streaming DSP with a graphical flowgraph editor.",
         "Signal Processing", ["c++", "python", "gui", "dsp"]),
        ("Sigrok / PulseView", "https://sigrok.org",
         "Vendor-neutral capture and analysis for logic analysers, oscilloscopes, and multimeters, with protocol decoders.",
         "Signal Processing", ["c", "gui", "instrumentation"]),
        ("PyVISA", "https://pyvisa.readthedocs.io",
         "Talks to lab instruments over GPIB, USB, serial, and Ethernet with one API; automates the whole bench.",
         "Signal Processing", ["python", "instrumentation"]),
        ("PlatformIO", "https://platformio.org",
         "Cross-platform embedded build system and library manager covering hundreds of boards with a real dependency model.",
         "Embedded & IoT", ["python", "embedded"]),
        ("Zephyr RTOS", "https://zephyrproject.org",
         "Scalable real-time OS with a strong device tree, driver model, and safety-certification path.",
         "Embedded & IoT", ["c", "rtos", "embedded"]),
        ("MicroPython", "https://micropython.org",
         "Python on microcontrollers, the fastest path from idea to a running sensor node.",
         "Embedded & IoT", ["python", "embedded"]),
        ("ESPHome", "https://esphome.io",
         "YAML-configured firmware for ESP32/ESP8266 sensor nodes with dozens of integrations and OTA updates.",
         "Embedded & IoT", ["yaml", "iot"]),
        ("Node-RED", "https://nodered.org",
         "Flow-based wiring of devices, APIs, and dashboards, excellent for lab data plumbing and prototypes.",
         "Embedded & IoT", ["javascript", "iot", "gui"]),
        ("Mosquitto", "https://mosquitto.org",
         "Lightweight MQTT broker, the default message bus for IoT and small telemetry systems.",
         "Embedded & IoT", ["c", "mqtt", "iot"]),
        ("Grafana", "https://grafana.com/oss/",
         "The standard open dashboarding layer for time-series sensor and process data.",
         "Embedded & IoT", ["go", "time-series", "dashboard"]),
        ("Pint", "https://pint.readthedocs.io",
         "Physical units with dimensional analysis and automatic conversion, catching the error class that destroys spacecraft.",
         "Numerical Computing", ["python", "units"]),
        ("SymPy", "https://www.sympy.org",
         "Symbolic algebra: derive equations, generate code from them, and check your algebra rather than trusting it.",
         "Numerical Computing", ["python", "symbolic"]),
        ("uncertainties", "https://pythonhosted.org/uncertainties/",
         "Propagates measurement uncertainty through calculations automatically, with correlation handling.",
         "Numerical Computing", ["python", "uncertainty"]),
        ("Unitful.jl", "https://github.com/PainterQubits/Unitful.jl",
         "Zero-overhead units in Julia, checked at compile time.",
         "Numerical Computing", ["julia", "units"]),
        ("open62541", "https://www.open62541.org",
         "Open C implementation of OPC UA for talking to industrial equipment, the modern plant-floor protocol.",
         "Industrial Protocols", ["c", "opc-ua", "scada"]),
        ("asyncua", "https://github.com/FreeOpcUa/opcua-asyncio",
         "Pure-Python OPC UA client and server, the practical way to pull process data into a notebook.",
         "Industrial Protocols", ["python", "opc-ua"]),
        ("pymodbus", "https://pymodbus.readthedocs.io",
         "Modbus TCP and RTU client and server; still how a startling amount of equipment communicates.",
         "Industrial Protocols", ["python", "modbus"]),
        ("FUXA", "https://github.com/frangoteam/FUXA",
         "Open web SCADA and HMI for small installations and teaching rigs.",
         "Industrial Protocols", ["javascript", "scada", "hmi"]),
        ("reliability", "https://reliability.readthedocs.io",
         "Weibull and other life-distribution fitting, accelerated life testing, and repairable systems analysis.",
         "Reliability", ["python", "reliability"]),
        ("lifelines", "https://lifelines.readthedocs.io",
         "Survival analysis, directly applicable to time-to-failure data and censored observations.",
         "Reliability", ["python", "statistics"]),
        ("Quarto", "https://quarto.org",
         "Publishing system for technical documents that executes Python, R, and Julia and outputs PDF, HTML, and Word.",
         "Documentation", ["markdown", "publishing"]),
        ("Sphinx", "https://www.sphinx-doc.org",
         "Documentation generator with cross-referencing, versioning, and excellent maths support.",
         "Documentation", ["python", "docs"]),
        ("MkDocs Material", "https://squidfunk.github.io/mkdocs-material/",
         "Fast, attractive documentation sites from plain Markdown with minimal configuration.",
         "Documentation", ["python", "docs"]),
        ("Mermaid", "https://mermaid.js.org",
         "Diagrams as text - flowcharts, sequence, Gantt - that render in GitHub and stay in version control.",
         "Documentation", ["javascript", "diagrams"]),
        ("Pandoc", "https://pandoc.org",
         "Converts between essentially every document format, the universal joint of technical writing.",
         "Documentation", ["cli", "conversion"]),
        ("OpenProject", "https://www.openproject.org",
         "Project management with Gantt charts, work packages, and time tracking; self-hostable.",
         "Project Management", ["ruby", "web"]),
        ("Plane", "https://plane.so",
         "Modern self-hostable issue and project tracker, a lighter alternative to Jira.",
         "Project Management", ["typescript", "web"]),
        ("NSPE Code of Ethics", "https://www.nspe.org/resources/ethics/code-ethics",
         "The reference engineering ethics code, plus a searchable archive of Board of Ethical Review cases.",
         "Engineering Ethics", ["reference", "free", "ethics"]),
        ("AIChE Code of Ethics", "https://www.aiche.org/about/governance/code-ethics",
         "Chemical engineering's professional code, with explicit process safety obligations.",
         "Engineering Ethics", ["reference", "free", "ethics"]),
        ("Online Ethics Center", "https://onlineethics.org",
         "Case studies, teaching materials, and discussion guides across engineering disciplines.",
         "Engineering Ethics", ["course", "free", "ethics"]),
        ("The Missing Semester", "https://missing.csail.mit.edu",
         "Shell, Git, debugging, and automation - the prerequisite engineers are rarely taught and always need.",
         "Learning Resources", ["course", "free"]),
        ("Software Carpentry", "https://carpentries.org",
         "Workshops and self-paced lessons for reproducible computing.",
         "Learning Resources", ["course", "free"]),
    ],
    TP: [
        ("mass_balance_notebook.ipynb", "https://github.com/OpenChemE/templates/blob/main/mass_balance_notebook.ipynb",
         "Steady-state material balances from a hand-checkable mixer to a three-unit flowsheet with recycle, plus a reaction example.",
         "Calculations", ["jupyter", "python", "numpy", "balances"]),
        ("reactor_design_skeleton.py", "https://github.com/OpenChemE/templates/blob/main/reactor_design_skeleton.py",
         "CSTR and PFR sizing for a liquid-phase reaction, with CSTRs-in-series comparison and a Levenspiel plot.",
         "Calculations", ["python", "scipy", "reactor-design"]),
        ("pid_tuning.py", "https://github.com/OpenChemE/templates/blob/main/pid_tuning.py",
         "FOPDT identification from a step test, then Ziegler-Nichols, Cohen-Coon, AMIGO, and IMC tuning compared on one loop.",
         "Calculations", ["python", "control", "pid"]),
        ("unit_conversions.py", "https://github.com/OpenChemE/templates/blob/main/unit_conversions.py",
         "Dependency-free conversions for flows, pressures, temperatures, viscosities, and duty, plus dimensionless groups.",
         "Calculations", ["python", "units", "no-dependencies"]),
        ("lab_report_template.md", "https://github.com/OpenChemE/templates/blob/main/lab_report_template.md",
         "Undergraduate lab report with YAML front matter, section guidance, and a worked uncertainty analysis.",
         "Documents", ["markdown", "pandoc", "report"]),
        ("eln_experiment_template.md", "https://github.com/OpenChemE/templates/blob/main/eln_experiment_template.md",
         "Electronic lab notebook entry: hypothesis, materials with lot numbers, execution log, deviations, amendments.",
         "Documents", ["markdown", "eln", "reproducibility"]),
        ("safety_checklist.md", "https://github.com/OpenChemE/templates/blob/main/safety_checklist.md",
         "HAZOP-style guide-word matrix and prompt list, with a laboratory and pilot-scale supplement.",
         "Documents", ["markdown", "safety", "hazop"]),
        ("aspen_simulation_tips.md", "https://github.com/OpenChemE/templates/blob/main/aspen_simulation_tips.md",
         "How to version-control Aspen and HYSYS work so simulation changes become reviewable diffs.",
         "Simulation", ["aspen", "git", "version-control"]),
        ("dwsim_simulation.dwxml", "https://github.com/OpenChemE/templates/blob/main/dwsim_simulation.dwxml",
         "Annotated DWSIM mixer and heater flowsheet in XML, showing why an open format is reviewable and a binary one is not.",
         "Simulation", ["dwsim", "xml", "flowsheet"]),
    ],
    WF: [
        ("conformer_generation_dft", "https://github.com/OpenChemE/workflows/tree/main/snakemake",
         "Snakemake pipeline: SMILES to standardised, MMFF-optimised, RMSD-pruned conformer ensembles with ORCA inputs written.",
         "Pipelines", ["snakemake", "rdkit", "conformers", "reproducibility"]),
        ("render_mol.yml", "https://github.com/OpenChemE/workflows/blob/main/github_actions/render_mol.yml",
         "GitHub Action rendering changed .mol/.sdf/.xyz files to SVG and validating them with RDKit on every pull request.",
         "CI Automation", ["github-actions", "openbabel", "rdkit", "ci"]),
        ("chem-toolkit Docker image", "https://github.com/OpenChemE/workflows/tree/main/docker",
         "Pinned container with RDKit, Open Babel, Cantera, CoolProp, the process engineering stack, Pyomo, and JupyterLab.",
         "Containers", ["docker", "rdkit", "cantera", "coolprop", "reproducibility"]),
    ],
}

records = []
for category, entries in DATA.items():
    for name, url, description, section, tags in entries:
        records.append({
            "name": name,
            "url": url,
            "description": description,
            "category": category,
            "section": section,
            "tags": tags,
        })

# Written to both copies of the site: the canonical one at the repository root
# (what Vercel serves) and the docs/ mirror (what GitHub Pages would serve).
# Paths are relative to this script so the repository can live anywhere.
here = pathlib.Path(__file__).resolve().parent
targets = [
    here / "docs" / "assets" / "data" / "resources.json",
    here.parent.parent / "public" / "assets" / "data" / "resources.json",
]

payload = json.dumps(records, indent=2, ensure_ascii=False) + "\n"
for out in targets:
    if not out.parent.is_dir():
        print(f"skipped (no such directory): {out}")
        continue
    out.write_text(payload)
    print(f"wrote {out}")
print(f"total records: {len(records)}")
for cat in DATA:
    print(f"  {cat:24s} {len(DATA[cat]):3d}")

# Guard against the mistakes that actually happen: duplicate names within a
# category, and non-http URLs.
seen = set()
for r in records:
    key = (r["category"], r["name"])
    assert key not in seen, f"duplicate: {key}"
    seen.add(key)
    assert r["url"].startswith("http"), f"bad url: {r['url']}"
print("validation: no duplicates, all URLs absolute")
