"""Write an ORCA input file for one conformer.

Called by the `prepare_dft_inputs` rule. Writes, does not run: DFT on a real
ensemble belongs in a cluster queue, and a Snakemake rule that quietly consumes
40 CPU-hours is a bad neighbour.

Also emits a Psi4 equivalent alongside, since Psi4 installs from conda and ORCA
does not -- useful if you want to run the small cases locally to check the
inputs make sense before submitting anything.
"""

from __future__ import annotations

import pathlib

params = snakemake.params  # noqa: F821
log_path = snakemake.log[0]  # noqa: F821
mol_id = snakemake.wildcards.mol_id  # noqa: F821


def log(msg: str) -> None:
    with open(log_path, "a") as fh:
        fh.write(msg + "\n")


def read_xyz(path: str) -> tuple[int, str, list[str]]:
    """Return (n_atoms, comment, [atom lines]) from an XYZ file."""
    lines = pathlib.Path(path).read_text().splitlines()
    n_atoms = int(lines[0].strip())
    comment = lines[1].strip()
    atoms = [ln.rstrip() for ln in lines[2 : 2 + n_atoms] if ln.strip()]
    if len(atoms) != n_atoms:
        raise ValueError(
            f"{path}: header says {n_atoms} atoms, found {len(atoms)} coordinate lines"
        )
    return n_atoms, comment, atoms


def build_orca_keywords() -> str:
    """Assemble the ORCA keyword line from config."""
    parts = ["! Opt", "Freq", params.method]

    # Composite methods (-3c) carry their own basis and dispersion correction.
    # Adding either again is at best redundant and at worst an error ORCA will
    # accept silently.
    is_composite = params.method.strip().endswith("-3c")

    if params.basis and not is_composite:
        parts.append(params.basis)
    elif params.basis and is_composite:
        log(f"  NOTE: basis {params.basis!r} ignored -- {params.method} is a "
            "composite method with its own basis set")

    if params.dispersion and not is_composite:
        parts.append(params.dispersion)

    if params.solvent:
        parts.append(params.solvent)

    parts.append("TightSCF")
    return " ".join(parts)


def main() -> None:
    n_atoms, comment, atoms = read_xyz(snakemake.input.xyz)  # noqa: F821

    log("=" * 70)
    log(f"DFT INPUT: {mol_id}")
    log("=" * 70)
    log(f"  atoms          {n_atoms}")
    log(f"  method         {params.method}")
    log(f"  solvent        {params.solvent or 'gas phase'}")
    log(f"  charge / mult  {params.charge} / {params.multiplicity}")

    if params.charge != 0 or params.multiplicity != 1:
        log("  NOTE: non-default charge or multiplicity applied to EVERY molecule.")
        log("  If your set is mixed, split it and run the pipeline per charge state.")

    # Cost scales roughly as N^3 to N^4 with basis functions. A warning here is
    # cheaper than a queue rejection tomorrow.
    if n_atoms > 100:
        log(f"  WARNING: {n_atoms} atoms with Opt + Freq is a large job. A frequency")
        log("  calculation on this is likely days, not hours. Consider dropping Freq")
        log("  unless you specifically need thermochemistry or a minimum confirmation.")

    keywords = build_orca_keywords()
    geometry = "\n".join(atoms)

    orca = f"""# ORCA input generated by conformer_generation_dft
# Molecule   : {mol_id}
# Conformer  : {pathlib.Path(snakemake.input.xyz).stem}
# Source     : {comment}
#
# Submit with:  orca {pathlib.Path(snakemake.output.inp).name} > {mol_id}.out
#
# Opt confirms the force-field geometry is a minimum on the DFT surface too --
# it often is not, and conformers can merge at this stage. Freq gives you the
# thermal corrections you need for a free-energy ranking, and confirms there
# are no imaginary frequencies. Drop Freq only if you have both covered.

{keywords}

%pal nprocs {params.nprocs} end
%maxcore {params.maxcore_mb}

%geom
  MaxIter 200
end

* xyz {params.charge} {params.multiplicity}
{geometry}
*
"""

    out_path = pathlib.Path(snakemake.output.inp)  # noqa: F821
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(orca)
    log(f"  wrote {out_path}")

    # --- Psi4 equivalent, for local checking -------------------------------
    psi4_method = params.method if not params.method.endswith("-3c") else "b3lyp-d3bj"
    psi4_basis = params.basis or "def2-SVP"
    psi4_path = out_path.with_suffix(".psi4.py")
    psi4_path.write_text(f'''"""Psi4 equivalent of {out_path.name}, for a local check.

    psi4 {psi4_path.name} -n {params.nprocs}

Note the method differs from the ORCA input: Psi4 has no composite -3c methods,
so this uses {psi4_method}/{psi4_basis} instead. The two will NOT give identical
energies. This file is for verifying the geometry and the setup, not for
producing numbers you would publish alongside the ORCA results.
"""

import psi4

psi4.set_memory("{params.maxcore_mb * params.nprocs} MB")
psi4.set_num_threads({params.nprocs})
psi4.core.set_output_file("{mol_id}_psi4.out", False)

mol = psi4.geometry("""
{params.charge} {params.multiplicity}
{geometry}
units angstrom
""")

psi4.set_options({{"basis": "{psi4_basis}", "scf_type": "df", "g_convergence": "gau_tight"}})

energy, wfn = psi4.optimize("{psi4_method}", return_wfn=True)
print(f"Optimised energy: {{energy:.8f}} Eh")
''')
    log(f"  wrote {psi4_path} (local cross-check)")


main()
