#!/usr/bin/env python3
"""Generate a detail page for every catalog resource, plus a comparison page.

    python scripts/generate_resource_pages.py            # write
    python scripts/generate_resource_pages.py --check    # fail if stale (CI)

Writes:
    public/r/<slug>.html      one page per resource (spec section 8.4)
    public/compare.html       side-by-side comparison (spec section 8.5)
    public/explore.html       browsable index of everything (spec section 8.3)

Design rule for these pages, from spec section 16.3: never show a bare
"verified" badge. Every claim on the page states what was checked, when, by
whom, and against what evidence — or says plainly that nothing was checked.
An unverified record must not look like a verified one.
"""

from __future__ import annotations

import argparse
import collections
import html
import pathlib
import sys
from typing import Any

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from openche import catalog  # noqa: E402

BANNER = "<!-- GENERATED by scripts/generate_resource_pages.py — do not edit. -->\n"


def e(text: Any) -> str:
    return html.escape(str(text), quote=True)


def head(title: str, description: str, depth: int = 0) -> str:
    """Shared <head>. `depth` sets how far the page is from the site root."""
    prefix = "../" * depth
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)}</title>
<meta name="description" content="{e(description)}">
<link rel="stylesheet" href="/assets/css/style.css">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>%E2%9A%97%EF%B8%8F</text></svg>">
<script>
  (function () {{
    var stored = null;
    try {{ stored = localStorage.getItem('theme'); }} catch (e) {{}}
    var dark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
    document.documentElement.dataset.theme = stored || (dark ? 'dark' : 'light');
  }})();
</script>
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header">
  <div class="container header-inner">
    <a class="brand" href="/">
      <span class="brand-mark" aria-hidden="true">&#9879;&#65039;</span>
      <span class="brand-text">
        <strong>Open ChemE Hub</strong>
        <small>Open resources for chemical engineering and the sciences next door</small>
      </span>
    </a>
    <nav class="site-nav" aria-label="Main">
      <button class="nav-toggle" aria-expanded="false" aria-controls="nav-links" aria-label="Toggle navigation">&#9776;</button>
      <ul id="nav-links">
        <li><a href="/">Home</a></li>
        <li><a href="/explore.html">Explore</a></li>
        <li><a href="/get-started.html">Get Started</a></li>
        <li><a href="/search.html">Search</a></li>
        <li><a href="https://github.com/OpenChemE" rel="noopener">GitHub</a></li>
        <li><button id="theme-toggle" class="theme-toggle" aria-label="Switch between light and dark theme" title="Switch theme">&#9682;</button></li>
      </ul>
    </nav>
  </div>
</header>
<main id="main">
"""


FOOTER = """</main>
<footer class="site-footer">
  <div class="container footer-legal">
    <p>
      Lists and documentation under <a href="https://creativecommons.org/licenses/by/4.0/" rel="noopener">CC BY 4.0</a>;
      code and templates under <a href="https://github.com/OpenChemE/blob/main/LICENSE" rel="noopener">MIT</a>.
      Linked projects retain their own licences.
    </p>
    <p class="disclaimer">
      Reference material only. Nothing here is engineering, clinical, or regulatory advice.
      Work affecting a real plant, patient, or safety case needs review by a qualified
      professional who is accountable for it.
    </p>
  </div>
</footer>
<script src="/assets/js/site.js" defer></script>
</body>
</html>
"""


def verification_block(rec: catalog.Record) -> str:
    """The trust panel. Spec section 16.3: never a bare tick."""
    v = rec.data.get("verification", {}) or {}
    tier = rec.tier
    label = catalog.VERIFICATION_LABELS[tier]
    blurb = catalog.VERIFICATION_BLURBS[tier]

    rows = [f"<p class='verify-what'>{e(blurb)}</p>"]

    if v.get("checked_at"):
        who = v.get("checked_by", "unrecorded")
        rows.append(f"<p class='verify-meta'>Checked {e(v['checked_at'])} by {e(who)}.</p>")
    elif tier == 0:
        rows.append(
            "<p class='verify-meta'>No check has been performed. "
            "<a href='https://github.com/OpenChemE/issues/new?template=add_resource.yml'>"
            "Help verify this record.</a></p>"
        )

    notes = v.get("notes") or []
    if notes:
        items = "".join(f"<li>{e(n)}</li>" for n in notes)
        rows.append(f"<details class='verify-notes'><summary>Verification notes</summary><ul>{items}</ul></details>")

    evidence = rec.data.get("evidence") or []
    if evidence:
        items = "".join(
            f"<li><a href='{e(ev['url'])}' rel='noopener'>{e(ev['type'].replace('-', ' '))}</a>"
            + (f" <span class='muted'>retrieved {e(ev['retrieved_at'])}</span>" if ev.get("retrieved_at") else "")
            + "</li>"
            for ev in evidence
        )
        rows.append(f"<div class='verify-evidence'><h3>Evidence</h3><ul>{items}</ul></div>")

    return (
        f"<aside class='verify verify-t{tier}' aria-label='Verification status'>"
        f"<div class='verify-head'><span class='verify-tier'>Tier {tier}</span>"
        f"<strong>{e(label)}</strong></div>"
        + "".join(rows)
        + "</aside>"
    )


def facts_table(rec: catalog.Record) -> str:
    d = rec.data
    access = d.get("access", {}) or {}
    lic = d.get("license", {}) or {}

    def unknown(value: Any) -> str:
        """Render an unconfirmed field visibly, not as a blank."""
        if value in (None, "", "unknown", "UNKNOWN", []):
            return "<span class='unknown' title='Not confirmed'>not confirmed</span>"
        if isinstance(value, list):
            return ", ".join(e(v) for v in value)
        return e(value)

    rows = [
        ("Kind", e(d.get("kind", "")).replace("-", " ")),
        ("Access model", unknown(access.get("model", "").replace("-", " ") or None)),
        ("Licence", unknown(lic.get("spdx"))),
        ("Maintenance", unknown(d.get("maintenance_status"))),
        ("Maturity", unknown(d.get("maturity"))),
        ("Platforms", unknown(d.get("platforms"))),
        ("Languages", unknown(d.get("languages"))),
        ("Audiences", unknown(d.get("audiences"))),
        ("Domains", ", ".join(e(x).replace("-", " ") for x in d.get("domains", []))),
    ]
    body = "".join(f"<tr><th scope='row'>{k}</th><td>{v}</td></tr>" for k, v in rows)
    return f"<table class='facts'><tbody>{body}</tbody></table>"


def bullet_section(title: str, items: list[str], css: str = "") -> str:
    if not items:
        return ""
    lis = "".join(f"<li>{e(i)}</li>" for i in items)
    return f"<section class='{css}'><h2>{e(title)}</h2><ul>{lis}</ul></section>"


def render_resource(rec: catalog.Record, by_slug: dict[str, catalog.Record]) -> str:
    d = rec.data
    title = f"{d['name']} · Open ChemE Hub"

    links = [f"<a class='btn btn-primary' href='{e(d['canonical_url'])}' rel='noopener'>Open project &rarr;</a>"]
    for field, label in (("repository_url", "Repository"), ("docs_url", "Documentation"), ("download_url", "Download")):
        if d.get(field):
            links.append(f"<a class='btn btn-secondary' href='{e(d[field])}' rel='noopener'>{label}</a>")

    alts = ""
    if d.get("alternatives"):
        items = []
        for slug in d["alternatives"]:
            other = by_slug.get(slug)
            if other:
                items.append(f"<li><a href='/r/{e(slug)}.html'>{e(other.name)}</a> — {e(other.data.get('summary',''))}</li>")
        if items:
            alts = f"<section><h2>Alternatives</h2><ul>{''.join(items)}</ul></section>"

    source = ""
    if d.get("source_list"):
        source = (
            f"<p class='muted small'>Imported from <code>{e(d['source_list'])}</code>"
            + (f", section &ldquo;{e(d['source_section'])}&rdquo;" if d.get("source_section") else "")
            + f". <a href='https://github.com/OpenChemE/blob/main/catalog/resources/{e(rec.slug)}.yaml'>"
            "View the canonical record</a>.</p>"
        )

    return (
        BANNER
        + head(title, d.get("summary", ""))
        + f"""
<div class="page-header">
  <div class="container narrow">
    <p class="eyebrow"><a href="/explore.html">Explore</a> / {e((d.get('categories') or [''])[0].replace('-', ' ').title())}</p>
    <h1>{e(d['name'])}</h1>
    <p class="lede">{e(d.get('summary', ''))}</p>
    <div class="hero-actions">{''.join(links)}</div>
  </div>
</div>

<div class="container narrow prose">
  {verification_block(rec)}
  <section><h2>At a glance</h2>{facts_table(rec)}</section>
  {bullet_section('Use this when', d.get('use_when', []))}
  {bullet_section('Do not use this when', d.get('avoid_when', []))}
  {bullet_section('Limitations', d.get('limitations', []), 'limitations')}
  {bullet_section('Getting started', d.get('install', []) + d.get('launch', []))}
  {alts}
  <section>
    <h2>Something wrong?</h2>
    <p>
      Metadata marked &ldquo;not confirmed&rdquo; is an open work item, not an oversight we are
      hiding. If you know the licence, the maintenance status, or a better description,
      <a href="https://github.com/OpenChemE/edit/main/catalog/resources/{e(rec.slug)}.yaml">edit
      the record</a> — it is one YAML file, and the lists and this page regenerate from it.
    </p>
    {source}
  </section>
</div>
"""
        + FOOTER
    )


def render_explore(records: list[catalog.Record]) -> str:
    by_domain: dict[str, list[catalog.Record]] = collections.defaultdict(list)
    for rec in records:
        for dom in rec.data.get("domains", []):
            by_domain[dom].append(rec)

    tiers = collections.Counter(r.tier for r in records)
    verified = sum(n for t, n in tiers.items() if t >= 2)

    sections = []
    for dom in sorted(by_domain):
        items = "".join(
            f"<li><a href='/r/{e(r.slug)}.html'>{e(r.name)}</a>"
            + (f" <span class='tier-chip tier-{r.tier}'>T{r.tier}</span>" if r.tier else "")
            + f"<span class='explore-summary'>{e(r.data.get('summary', ''))}</span></li>"
            for r in sorted(by_domain[dom], key=lambda x: x.name.lower())
        )
        sections.append(
            f"<section id='{e(dom)}'><h2>{e(dom.replace('-', ' ').title())} "
            f"<span class='muted'>({len(by_domain[dom])})</span></h2>"
            f"<ul class='explore-list'>{items}</ul></section>"
        )

    return (
        BANNER
        + head("Explore · Open ChemE Hub", "Every resource in the Open ChemE Hub catalog, by domain.")
        + f"""
<div class="page-header">
  <div class="container narrow">
    <h1>Explore</h1>
    <p class="lede">
      Every one of the {len(records)} records in the catalog, grouped by domain. For filtered
      and ranked results use <a href="/search.html">search</a>; this page is the
      complete browsable index.
    </p>
  </div>
</div>

<div class="container prose">
  <div class="callout">
    <p>
      <strong>{verified} of {len(records)} records have been independently verified
      (tier 2 or above).</strong> The rest carry metadata imported from the original
      lists and marked <em>not confirmed</em> where it was never recorded.
      That is the honest state of the catalog today, and
      <a href="/../docs/verification-methodology.md">the methodology</a> explains how a
      record moves up a tier.
    </p>
  </div>
  {''.join(sections)}
</div>
"""
        + FOOTER
    )


def render_compare(records: list[catalog.Record], slugs: list[str]) -> str:
    by_slug = {r.slug: r for r in records}
    chosen = [by_slug[s] for s in slugs if s in by_slug]
    if not chosen:
        chosen = records[:3]

    dimensions: list[tuple[str, Any]] = [
        ("Summary", lambda r: r.data.get("summary", "")),
        ("Kind", lambda r: r.data.get("kind", "").replace("-", " ")),
        ("Access model", lambda r: (r.data.get("access") or {}).get("model", "unknown").replace("-", " ")),
        ("Licence", lambda r: (r.data.get("license") or {}).get("spdx", "UNKNOWN")),
        ("Maintenance", lambda r: r.data.get("maintenance_status", "unknown")),
        ("Platforms", lambda r: ", ".join(r.data.get("platforms") or []) or "unknown"),
        ("Languages", lambda r: ", ".join(r.data.get("languages") or []) or "unknown"),
        ("Verification", lambda r: f"Tier {r.tier} — {catalog.VERIFICATION_LABELS[r.tier]}"),
    ]

    def cell(value: Any) -> str:
        """Render an unconfirmed value visibly rather than as an empty cell."""
        text = str(value).strip()
        if text.lower() in {"unknown", "not confirmed", ""}:
            return "<td><span class='unknown'>not confirmed</span></td>"
        return f"<td>{e(text)}</td>"

    header = "".join(f"<th scope='col'><a href='/r/{e(r.slug)}.html'>{e(r.name)}</a></th>" for r in chosen)
    rows = []
    for label, fn in dimensions:
        cells = "".join(cell(fn(r)) for r in chosen)
        rows.append(f"<tr><th scope='row'>{e(label)}</th>{cells}</tr>")

    return (
        BANNER
        + head("Compare · Open ChemE Hub", "Side-by-side comparison of open process simulation tools.")
        + f"""
<div class="page-header">
  <div class="container narrow">
    <h1>Compare</h1>
    <p class="lede">
      Structured metadata placed side by side. No scores and no rankings — the spec is
      explicit about that, and a single number would hide exactly the trade-offs you came
      here to see.
    </p>
  </div>
</div>

<div class="container prose">
  <div class="callout callout-warning">
    <p>
      <strong>Read the verification row first.</strong> A field reading &ldquo;not
      confirmed&rdquo; means nobody has checked it, not that the answer is no. Comparing
      unconfirmed metadata tells you what the catalog currently records, which is not the
      same as what is true.
    </p>
  </div>

  <table class="compare">
    <thead><tr><th scope="col">Dimension</th>{header}</tr></thead>
    <tbody>{''.join(rows)}</tbody>
  </table>

  <h2>Editorial notes</h2>
  <p>
    Structured fields cannot capture everything that matters when choosing between these.
    Notes below are explicitly editorial — human judgement, not metadata:
  </p>
  <ul>
    <li><strong>GUI versus code.</strong> A graphical flowsheeter and a Python framework
    solve the same equations and suit completely different workflows. Neither is more
    &ldquo;advanced&rdquo;.</li>
    <li><strong>Convergence behaviour</strong> on recycle-heavy flowsheets varies widely and
    is not captured by any field here. Try your own hardest case before committing.</li>
    <li><strong>Community size</strong> determines how fast you get unstuck, and is often
    the deciding factor for a student on a deadline.</li>
  </ul>
  <p class="muted small">
    To compare a different set, edit <code>COMPARE_SETS</code> in
    <code>scripts/generate_resource_pages.py</code>. An interactive picker is Phase 1 work.
  </p>
</div>
"""
        + FOOTER
    )


# The default comparison set: the open flowsheeting options a reader most often
# has to choose between.
COMPARE_SETS: list[str] = ["dwsim", "coco-simulator", "idaes-pse", "openmodelica"]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    records = catalog.load_resources()
    by_slug = {r.slug: r for r in records}

    outputs: dict[pathlib.Path, str] = {}
    for rec in records:
        outputs[catalog.SITE_RESOURCE_DIR / f"{rec.slug}.html"] = render_resource(rec, by_slug)
    outputs[catalog.SITE_DIR / "explore.html"] = render_explore(records)
    outputs[catalog.SITE_DIR / "compare.html"] = render_compare(records, COMPARE_SETS)

    if args.check:
        stale = [p for p, content in outputs.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != content]
        existing = set(catalog.SITE_RESOURCE_DIR.glob("*.html"))
        orphans = existing - set(outputs)
        if stale or orphans:
            for p in sorted(stale)[:10]:
                print(f"  stale   {p.relative_to(catalog.ROOT)}")
            for p in sorted(orphans)[:10]:
                print(f"  orphan  {p.relative_to(catalog.ROOT)} (no matching record)")
            print(f"\nfail  {len(stale)} stale, {len(orphans)} orphaned page(s)")
            print("      Run: python scripts/generate_resource_pages.py")
            return 1
        print(f"  ok     {len(outputs)} generated page(s) up to date")
        return 0

    catalog.SITE_RESOURCE_DIR.mkdir(parents=True, exist_ok=True)
    # Remove pages whose record was deleted, so the site never serves a page
    # for something no longer in the catalog.
    for orphan in set(catalog.SITE_RESOURCE_DIR.glob("*.html")) - set(outputs):
        orphan.unlink()
        print(f"  removed {orphan.relative_to(catalog.ROOT)}")

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    print(f"  wrote  {len(records)} resource page(s) to public/r/")
    print("  wrote  public/explore.html")
    print("  wrote  public/compare.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
